### ISSUE TITLE
bind resources from cli

### ISSUE THREAD

**Issue by quiye** [quiye/varust#8]
input `sample.yaml`
```yaml
dev:
  SECRET_KEY: SECRET_DEV
prod:
  SECRET_KEY: SECRET_PROD
```

bind like
```
$ varust sample.yaml dev --bind SECRET_DEV:secret_key_payload
SECRET_KEY=secret_key_payload
```
